twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['form/theme.html.twig']
    globals:
        app_devise: '%app.devise%'
        pressing:
            nom: '%app.pressing.nom%'
            adresse: '%app.pressing.adresse%'
            telephone: '%app.pressing.telephone%'
when@test:
    twig:
        strict_variables: true
